---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "programming"
baseurl: "http://vojtechvitek.github.io/blog"
title: "Vojtech Vitek - blog"
canonifyurls: true
...
